# Generated by Django 2.1.2 on 2019-04-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=300)),
                ('article_describe', models.CharField(max_length=255)),
                ('article_content_md', models.TextField()),
                ('article_author', models.PositiveIntegerField()),
                ('article_status', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('article_click', models.IntegerField()),
                ('article_comment', models.IntegerField()),
                ('article_favour', models.IntegerField()),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('comment_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_status', models.IntegerField(blank=True, null=True)),
                ('comment_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArticlePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_tag', models.CharField(max_length=20)),
                ('place_value', models.CharField(max_length=100)),
                ('place_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_place',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArticleStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_name', models.CharField(max_length=50)),
                ('statistics_type', models.IntegerField()),
                ('statistics_value', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_statistics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('atid', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.IntegerField()),
                ('tag_content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'article_tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('ac_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
                ('used', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=255)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'friend_link',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('operation', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_content', models.CharField(max_length=20)),
                ('tag_time', models.IntegerField()),
            ],
            options={
                'db_table': 'tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('token', models.CharField(blank=True, max_length=128, null=True)),
                ('header_url', models.CharField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('last_login_address', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField()),
                ('admin', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('master_name', models.CharField(blank=True, max_length=50, null=True)),
                ('master_email', models.CharField(blank=True, max_length=200, null=True)),
                ('website_about', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website',
                'managed': True,
            },
        ),
    ]
