# Generated by Django 2.1.2 on 2019-04-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='articleplace',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='articlestatistics',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='articletag',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authcode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='friendlink',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'managed': False},
        ),
    ]
